services:
  app:
    build: .
    ports:
      - "3050:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/data/prod.db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - STICKER_PACK_NAME=higorlino.dev bot
      - STICKER_AUTHOR=higorlino.dev
      - STORAGE_PATH=/app/storage
      - SESSIONS_PATH=/app/sessions
    volumes:
      - sessions:/app/sessions
      - storage:/app/storage
      - sqldata:/app/data
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:8-alpine
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  sessions:
  storage:
  redis_data:
  sqldata:
