services:
  app:
    build: .
    env_file:
      - .env
    volumes:
      - sessions:/app/sessions
      - storage:/app/storage
      - sqldata:/app/data
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:8-alpine
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  sessions:
  storage:
  redis_data:
  sqldata:
