services:
  caddy:
    image: caddy:2-alpine
    ports:
      - "8880:80"
      - "8443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

  app:
    build: .
    env_file:
      - .env
    volumes:
      - sessions:/app/sessions
      - storage:/app/storage
      - sqldata:/app/data
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:8-alpine
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  sessions:
  storage:
  redis_data:
  sqldata:
  caddy_data:
  caddy_config:
